### ISSUE TITLE
How to fix this error?

### ISSUE THREAD

**Issue by Elaineok** [liuweide01/RPNet-Weakly-Supervised-Segmentation#1]
When I run this program, the following error occurs.

File "xxxx/net/resnet50_cam.py", line 106, in cal_cos_vector
    area = F.avg_pool2d(mask, x.shape[-2:]) * h * w + 0.0005
**RuntimeError: _thnn_avg_pool2d_forward not supported on CUDAType for Byte**

**Comment by liuweide01** [comment]
> When I run this program, the following error occurs.
> 
> File "xxxx/net/resnet50_cam.py", line 106, in cal_cos_vector area = F.avg_pool2d(mask, x.shape[-2:]) * h * w + 0.0005 **RuntimeError: _thnn_avg_pool2d_forward not supported on CUDAType for Byte**

You can try to change the pytorch version, or convert to float, e.g., data.astype(float)

**Comment by Elaineok** [comment]
I first tried to convert it to floating point, but it didn't solve it.
After that, pytorch 1.4.0 was used to solve this problem perfectly. Thanks
for your reply.

LiuWeide ***@***.***> 于2021年10月17日周日 上午10:21写道：
