### ISSUE TITLE
table1 result

### ISSUE THREAD

**Issue by geek-APTX4869** [liuweide01/RPNet-Weakly-Supervised-Segmentation#3]
Dear author：
  如何使用Base+RPNet+BR，run_sample.py是用irn生成伪mask吗?能不能提供代码让我学习一下呀？

**Comment by liuweide01** [comment]
in run_sample.py, the line   [      step.make_sem_seg_labels.run(args)](https://github.com/liuweide01/RPNet-Weakly-Supervised-Segmentation/blob/52d74e3057260bf94d84f9fbf9af5ac9a2b76555/run_sample.py#L116C9-L116C43)  step.make_sem_seg_labels.run(args)
